//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Tools.AutoUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Tools.AutoUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gewählte Paket kann nicht abgewählt werden. Folgende Pakete haben Abhängigkeiten zu diesem:
        ///{0}
        ///
        ///Möchten Sie dieses Paket dennoch abwählen? Alle abhängigen Pakete werden dann automatisch mit abgewählt..
        /// </summary>
        internal static string CannotUnscheduleBecauseOfExistingDependenciesMessage {
            get {
                return ResourceManager.GetString("CannotUnscheduleBecauseOfExistingDependenciesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gewählte Paket ist gekennzeichnet als &quot;veraltet&quot; (deprecated). Dies bedeutet, dass es sich nicht mehr in aktiver Entwicklung befindet und nur aus Kompatibilitätsgründen noch enthalten ist. Wenn Fragen hierzu bestehen, wenden Sie sich bitte an das AlarmWorkflow-Team. Danke.
        ///
        ///Wenn Sie möchten, können Sie fortfahren..
        /// </summary>
        internal static string PackageIsDeprecatedWarningMessage {
            get {
                return ResourceManager.GetString("PackageIsDeprecatedWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gewählte Paket ist gekennzeichnet als &quot;work in progress&quot; (WIP). Dies bedeutet, dass die es sich noch in der Entstehungsphase befindet, weswegen einige Funktionen möglicherweise nicht ausgereift sind. Benutzung dies Paketes geschieht auf eigene Gefahr.
        ///
        ///Sie sind herzlich eingeladen, dieses Paket zu testen und Fehler bzw. Anregungen an das Team zu senden. 
        ///
        ///Wenn Sie möchten, können Sie fortfahren..
        /// </summary>
        internal static string PackageIsWIPWarningMessage {
            get {
                return ResourceManager.GetString("PackageIsWIPWarningMessage", resourceCulture);
            }
        }
    }
}
